// <auto-generated />
using GeekShopping.ProductAPI.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20220927162319_SeedProduct")]
    partial class SeedProduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            CategoryName = "camisa",
                            Description = "alguma coisa descrita aqui",
                            ImageUrl = "ainda nao tem",
                            Name = "Name",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "camisa",
                            Description = "alguma coisa descrita aqui",
                            ImageUrl = "ainda nao tem",
                            Name = "Name",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "camisa",
                            Description = "alguma coisa descrita aqui",
                            ImageUrl = "ainda nao tem",
                            Name = "Name",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "camisa",
                            Description = "alguma coisa descrita aqui",
                            ImageUrl = "ainda nao tem",
                            Name = "Name",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "camisa",
                            Description = "alguma coisa descrita aqui",
                            ImageUrl = "ainda nao tem",
                            Name = "Name",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "camisa",
                            Description = "alguma coisa descrita aqui",
                            ImageUrl = "ainda nao tem",
                            Name = "Name",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "camisa",
                            Description = "alguma coisa descrita aqui",
                            ImageUrl = "ainda nao tem",
                            Name = "Name",
                            Price = 69.9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
